<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>Exercice2 ToodoList KRDS</title>
	<!-- Call the CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/7.0.0/normalize.min.css"> <!-- NORMALIZE -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"> <!-- FONT AWESOME -->
	<link href="https://fonts.googleapis.com/css?family=Shadows+Into+Light" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Oswald|Shadows+Into+Light" rel="stylesheet">
	<link rel="stylesheet" href="application/www/css/style.css">

    <!-- Call the jQuery CDN -->
    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4="
      crossorigin="anonymous"></script>

     <script src="application/www/js/events.js"></script> <!-- Events of the DOM -->
</head>

<body>
    <header>
        <h1>Test2 for Krds</h1>
    </header>

    <main>
        <section id="tasks_list_ul">
			<h2>To-Do List</h2>
            <ul>
                <?php
                foreach ($tasks as $task):
                 ?>

                 <li>
                     <em data-index="<?= $task['idTask']; ?>">
                         <?= $task['taskContent']; ?>
                     </em>
                 </li>

                <?php
                endforeach
                 ?>
            </ul>
        </section>

		<section id="todolist_form" class="hide">
			<form id="addform" action="application/controllers/addTask.php" method="post">
				<label for="task_content">Add a new task in the To-Do List!</label>
				<input type="text" name="task_content" id="task_content" placeholder=" What do you have to do?" required/>
				<input type="submit" name="Save" value="Save" id="save_task"> <!-- Save-Task button -->
			</form>
		</section>

		<section>
			<button type="button" name="button" id="add_task"><i class="fa fa-plus" aria-hidden="true"></i></button> <!-- Add-Task button -->
            <form action="application/controllers/deleteTasks.php" method="post">
			      <button type="submit" name="button" id="delete_task"><i class="fa fa-trash" aria-hidden="true"></i></button> <!-- Delete-Task button -->
            </form>
		</section>
    </main>

    <script src="application/www/js/main.js"></script>
</body>
